from typing import TypedDict, List, Annotated
import operator

class AgentState(TypedDict):
    #class to hold the shared memory of our agents
    resume_text: str
    jd_text: str
    graph_cypher: str           # Generated by Constructor
    auditor_report: str        # Hard skill comparison
    skeptic_critique: str      # Red flags
    enthusiast_pitch: str      # Potential/Growth
    final_verdict: str         # Lead Recruiter's decision