from typing import TypedDict, List


class AgentState(TypedDict):
    #shared memoery state for the agents to use
    resume_text: str
    jd_text: str
    candidate_id: str                  # UUID generated by orchestrator
    graph_queries: List[str]           # Cypher queries from Constructor
    auditor_report: dict               # Structured skills gap analysis
    skeptic_critique: dict             # Red flags and risk assessment
    enthusiast_pitch: dict             # Growth potential and defenses
    final_verdict: str                 # Lead Recruiter's decision