from typing import TypedDict, List


class AgentState(TypedDict):
    """Shared memory that flows through the orchestration pipeline.

    Each agent reads from and writes to specific keys so the orchestrator
    can track intermediate results and resume on partial failures.
    """
    resume_text: str
    jd_text: str
    candidate_id: str                  # UUID generated by orchestrator
    graph_queries: List[str]           # Cypher queries from Constructor
    auditor_report: dict               # Structured skills gap analysis
    skeptic_critique: dict             # Red flags and risk assessment
    enthusiast_pitch: dict             # Growth potential and defenses
    final_verdict: str                 # Lead Recruiter's decision